### ISSUE TITLE
Pattern file collides with NLog config

### ISSUE THREAD

**Issue by tap-absg** [cezarypiatek/VanillaTransformer#2]
Hello,

I want to say that I find this neat and very easy to use. 
However I am using NLog, and NLog.config uses ${} syntax for its local variables and logger definitions. This is unfortunate as this interferes with VanillaTransformer. The issue looks to be with the parser for the pattern file,as NLog.config has parts that look like the following:

    <default-target-parameters xsi:type="File" 
            keepFileOpen="false"
            layout="${longdate} - ${uppercase:${level}} - ${threadid} - ${callsite} - ${message}${onexception:${newline}EXCEPTION\: ${exception:format=ToString}}"
            />

I do realize I can fork and submit a pull for my issue, and I may do that. I was wondering if there is a workaround for this, before I start digging into the code.

Thanks,
Tomaso

**Comment by cezarypiatek** [comment]
Hi
The type of the placeholder is configurable through the "TransformerName" parameter of VanillaTransformerTask. Unfortunately, there is currently only single transformer implementation - DollarPlaceholderTransformer. You can add your custom implementation of ITransformer (For example HashPlaceholderTransform for #{placeholder} ) and set "TransformerName" parameter to full name of your implementation class.  I will gladly accept your pull request.

**Comment by tap-absg** [comment]
I realized that after digging through the code, and I implemented a new ITransformer with a different syntax which solves my issues. I also exposed the TransformerName property in several of the powershell cmdlets and methods so you have the option of what Transformer to use.

If I am reading the ReflectionHelper correctly, your code is only able to load additional ITransformer implementations that are in the assembly; is that correct? If so, it might be a solution to enable the reflection to load form any assembly containing an ITransformer, that way anyone can create a custom replacement syntax and just configure the task as you can now.

**Comment by cezarypiatek** [comment]
I can add a mechanism to load transformers from external libraries but the crucial idea of the VanillaTransformer is to keep it simple. Anyway I will take this functionality under advisement.  Other option is to make a variable placeholder pattern as a configurable options (create a GenericPlaceholderTransformer).  What do you think about that approach?

Could you send me a pull request with your changes?

**Comment by tap-absg** [comment]
I just submitted the Pull Request. It all worked locally for me, but please verify.

**Comment by cezarypiatek** [comment]
I needed to fix some things. For more details check commits ef311008dc70d4ba9481abdacdd1d76d403d5df3 and
21f89c60082ef56838da5d3f48eb38db3b6b31b3

Anyway, thanks for your collaboration.

**Comment by cezarypiatek** [comment]
FIXED #3
